
package cat.institutmarianao.items.web.jaxws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "ItemService", targetNamespace = "http://impl.service.ws.items.institutmarianao.cat/", wsdlLocation = "http://localhost:8080/items.ws/ItemService?wsdl")
public class ItemService
    extends Service
{

    private static final URL ITEMSERVICE_WSDL_LOCATION;
    private static final WebServiceException ITEMSERVICE_EXCEPTION;
    private static final QName ITEMSERVICE_QNAME = new QName("http://impl.service.ws.items.institutmarianao.cat/", "ItemService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/items.ws/ItemService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ITEMSERVICE_WSDL_LOCATION = url;
        ITEMSERVICE_EXCEPTION = e;
    }

    public ItemService() {
        super(__getWsdlLocation(), ITEMSERVICE_QNAME);
    }

    public ItemService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ITEMSERVICE_QNAME, features);
    }

    public ItemService(URL wsdlLocation) {
        super(wsdlLocation, ITEMSERVICE_QNAME);
    }

    public ItemService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ITEMSERVICE_QNAME, features);
    }

    public ItemService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ItemService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ItemServiceEndpoint
     */
    @WebEndpoint(name = "ItemServiceEndpointImplPort")
    public ItemServiceEndpoint getItemServiceEndpointImplPort() {
        return super.getPort(new QName("http://impl.service.ws.items.institutmarianao.cat/", "ItemServiceEndpointImplPort"), ItemServiceEndpoint.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ItemServiceEndpoint
     */
    @WebEndpoint(name = "ItemServiceEndpointImplPort")
    public ItemServiceEndpoint getItemServiceEndpointImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl.service.ws.items.institutmarianao.cat/", "ItemServiceEndpointImplPort"), ItemServiceEndpoint.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ITEMSERVICE_EXCEPTION!= null) {
            throw ITEMSERVICE_EXCEPTION;
        }
        return ITEMSERVICE_WSDL_LOCATION;
    }

}
